/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab8;

import java.awt.EventQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author purusharth
 */


public class lab8_question1 extends javax.swing.JPanel {

    /**
     * Creates new form Test4
     */
    
    
    public lab8_question1() {
        initComponents();
        Connect();
    }
    
    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            JFrame f = new JFrame();
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            f.add(new lab8_question1());
            f.pack();
            f.setVisible(true);
        });
    
        
    }

    static Connection con;
    static PreparedStatement pst;
    static ResultSet rs;
    
    public static void Connect(){
        try {
            //loading the driver class
            Class.forName("com.mysql.cj.jdbc.Driver");
            //initializing the database connection
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/lab8", "root", "");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sidePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        adminTab = new javax.swing.JButton();
        attendeeTab = new javax.swing.JButton();
        outerPanel = new javax.swing.JPanel();
        attendeePanel = new javax.swing.JPanel();
        outerAdd = new javax.swing.JButton();
        outerUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        outerSearch = new javax.swing.JButton();
        outerDelete = new javax.swing.JButton();
        outerStatistics = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtCountry = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        countrySearchBtn = new javax.swing.JButton();
        countrySearch = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        updateName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        updateCountry = new javax.swing.JComboBox<>();
        updateEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        updateNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deleteTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        deleteId = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        statisticsPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        sidePanel.setBackground(new java.awt.Color(153, 0, 153));
        sidePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidePanelMouseDragged(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(167, 131, 167));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Attendees Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        adminTab.setBackground(new java.awt.Color(153, 0, 153));
        adminTab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminTab.setForeground(new java.awt.Color(255, 255, 255));
        adminTab.setText("Admin");
        adminTab.setBorder(null);
        adminTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTabActionPerformed(evt);
            }
        });

        attendeeTab.setBackground(new java.awt.Color(153, 0, 153));
        attendeeTab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attendeeTab.setForeground(new java.awt.Color(255, 255, 255));
        attendeeTab.setText("Attendee");
        attendeeTab.setBorder(null);
        attendeeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeeTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(attendeeTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(adminTab, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(attendeeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(sidePanel);

        outerPanel.setBackground(new java.awt.Color(255, 255, 255));
        outerPanel.setLayout(new java.awt.CardLayout());

        attendeePanel.setBackground(new java.awt.Color(255, 255, 255));

        outerAdd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        outerAdd.setForeground(new java.awt.Color(153, 0, 153));
        outerAdd.setText("New Registration");
        outerAdd.setBorder(null);
        outerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerAddActionPerformed(evt);
            }
        });

        outerUpdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        outerUpdate.setForeground(new java.awt.Color(153, 0, 153));
        outerUpdate.setText("Update your details");
        outerUpdate.setBorder(null);
        outerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel4.setText("Welcome to Christ University!");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel5.setText("Proceed with your request...");

        javax.swing.GroupLayout attendeePanelLayout = new javax.swing.GroupLayout(attendeePanel);
        attendeePanel.setLayout(attendeePanelLayout);
        attendeePanelLayout.setHorizontalGroup(
            attendeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attendeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outerAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addComponent(outerUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendeePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(attendeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)))
                .addGap(191, 191, 191))
        );
        attendeePanelLayout.setVerticalGroup(
            attendeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendeePanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(53, 53, 53)
                .addComponent(outerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(outerUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        outerPanel.add(attendeePanel, "card3");

        adminPanel.setBackground(new java.awt.Color(255, 255, 255));

        outerSearch.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        outerSearch.setForeground(new java.awt.Color(153, 0, 153));
        outerSearch.setText("Search");
        outerSearch.setBorder(null);
        outerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerSearchActionPerformed(evt);
            }
        });

        outerDelete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        outerDelete.setForeground(new java.awt.Color(153, 0, 153));
        outerDelete.setText("Delete");
        outerDelete.setBorder(null);
        outerDelete.setDoubleBuffered(true);
        outerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerDeleteActionPerformed(evt);
            }
        });

        outerStatistics.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        outerStatistics.setForeground(new java.awt.Color(153, 0, 153));
        outerStatistics.setText("Statistics");
        outerStatistics.setBorder(null);
        outerStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerStatisticsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel1.setText("What operation do you want to perform?");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 16)); // NOI18N
        jLabel3.setText("Welcome Back!");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outerSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outerDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outerStatistics, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addGap(0, 157, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(outerStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outerDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        outerPanel.add(adminPanel, "card2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Full Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Country");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("E-mail");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Phone Number");

        txtCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia (Czech Republic)", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor (Timor-Leste)", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia (formerly Macedonia)", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" }));
        txtCountry.setSelectedIndex(-1);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(txtName))
                .addGap(42, 42, 42)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(259, 259, 259))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        outerPanel.add(addPanel, "card4");

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Country", "Contact Number", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(searchTable);
        if (searchTable.getColumnModel().getColumnCount() > 0) {
            searchTable.getColumnModel().getColumn(2).setHeaderValue("Country");
            searchTable.getColumnModel().getColumn(3).setHeaderValue("Contact Number");
            searchTable.getColumnModel().getColumn(4).setHeaderValue("E-mail");
        }

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Search (Email)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Records");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        countrySearchBtn.setText("Search");
        countrySearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrySearchBtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Search (Country)");

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel22.setText("or");

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(countrySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(countrySearchBtn))
                    .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewPanelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(searchBtn))
                        .addGroup(viewPanelLayout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(jLabel11))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(289, 289, 289))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(10, 10, 10)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countrySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countrySearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        outerPanel.add(viewPanel, "card5");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Full Name");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Country");

        updateCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    Afghanistan", "    Albania", "    Algeria", "    Andorra", "    Angola", "    Antigua and Barbuda", "    Argentina", "    Armenia", "    Australia", "    Austria", "    Azerbaijan", "    Bahamas", "    Bahrain", "    Bangladesh", "    Barbados", "    Belarus", "    Belgium", "    Belize", "    Benin", "    Bhutan", "    Bolivia", "    Bosnia and Herzegovina", "    Botswana", "    Brazil", "    Brunei", "    Bulgaria", "    Burkina Faso", "    Burundi", "    Cabo Verde", "    Cambodia", "    Cameroon", "    Canada", "    Central African Republic", "    Chad", "    Chile", "    China", "    Colombia", "    Comoros", "    Congo (Congo-Brazzaville)", "    Costa Rica", "    Croatia", "    Cuba", "    Cyprus", "    Czechia (Czech Republic)", "    Denmark", "    Djibouti", "    Dominica", "    Dominican Republic", "    East Timor (Timor-Leste)", "    Ecuador", "    Egypt", "    El Salvador", "    Equatorial Guinea", "    Eritrea", "    Estonia", "    Eswatini", "    Ethiopia", "    Fiji", "    Finland", "    France", "    Gabon", "    Gambia", "    Georgia", "    Germany", "    Ghana", "    Greece", "    Grenada", "    Guatemala", "    Guinea", "    Guinea-Bissau", "    Guyana", "    Haiti", "    Honduras", "    Hungary", "    Iceland", "    India", "    Indonesia", "    Iran", "    Iraq", "    Ireland", "    Israel", "    Italy", "    Ivory Coast", "    Jamaica", "    Japan", "    Jordan", "    Kazakhstan", "    Kenya", "    Kiribati", "    Korea, North", "    Korea, South", "    Kosovo", "    Kuwait", "    Kyrgyzstan", "    Laos", "    Latvia", "    Lebanon", "    Lesotho", "    Liberia", "    Libya", "    Liechtenstein", "    Lithuania", "    Luxembourg", "    Madagascar", "    Malawi", "    Malaysia", "    Maldives", "    Mali", "    Malta", "    Marshall Islands", "    Mauritania", "    Mauritius", "    Mexico", "    Micronesia", "    Moldova", "    Monaco", "    Mongolia", "    Montenegro", "    Morocco", "    Mozambique", "    Myanmar (Burma)", "    Namibia", "    Nauru", "    Nepal", "    Netherlands", "    New Zealand", "    Nicaragua", "    Niger", "    Nigeria", "    North Macedonia (formerly Macedonia)", "    Norway", "    Oman", "    Pakistan", "    Palau", "    Panama", "    Papua New Guinea", "    Paraguay", "    Peru", "    Philippines", "    Poland", "    Portugal", "    Qatar", "    Romania", "    Russia", "    Rwanda", "    Saint Kitts and Nevis", "    Saint Lucia", "    Saint Vincent and the Grenadines", "    Samoa", "    San Marino", "    Sao Tome and Principe", "    Saudi Arabia", "    Senegal", "    Serbia", "    Seychelles", "    Sierra Leone", "    Singapore", "    Slovakia", "    Slovenia", "    Solomon Islands", "    Somalia", "    South Africa", "    South Sudan", "    Spain", "    Sri Lanka", "    Sudan", "    Suriname", "    Sweden", "    Switzerland", "    Syria", "    Taiwan", "    Tajikistan", "    Tanzania", "    Thailand", "    Togo", "    Tonga", "    Trinidad and Tobago", "    Tunisia", "    Turkey", "    Turkmenistan", "    Tuvalu", "    Uganda", "    Ukraine", "    United Arab Emirates", "    United Kingdom", "    United States", "    Uruguay", "    Uzbekistan", "    Vanuatu", "    Vatican City", "    Venezuela", "    Vietnam", "    Yemen", "    Zambia", "    Zimbabwe", " " }));
        updateCountry.setSelectedIndex(-1);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("E-mail");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Phone Number");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel16.setText("Update your details");

        jLabel17.setText("Note: Make sure you are entering the correct email address.");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(259, 259, 259))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updatePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(updateNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(updateName)))
                                    .addComponent(jLabel12))
                                .addGap(42, 42, 42)
                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)))))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel16)
                .addGap(55, 55, 55)
                .addComponent(jLabel17)
                .addGap(51, 51, 51)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(updateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(updateCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(updateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(53, 53, 53))
        );

        outerPanel.add(updatePanel, "card6");

        deleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Country", "Contact Number", "E-mail"
            }
        ));
        jScrollPane2.setViewportView(deleteTable);
        if (deleteTable.getColumnModel().getColumnCount() > 0) {
            deleteTable.getColumnModel().getColumn(2).setHeaderValue("Country");
            deleteTable.getColumnModel().getColumn(3).setHeaderValue("Contact Number");
            deleteTable.getColumnModel().getColumn(4).setHeaderValue("E-mail");
        }

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Records");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Id (to be deleted)");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(deleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel18)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        outerPanel.add(deletePanel, "card7");

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel20.setText("Country-wise attendees");

        statsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Country", "Count(Id)"
            }
        ));
        jScrollPane3.setViewportView(statsTable);

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        statisticsPanelLayout.setVerticalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        outerPanel.add(statisticsPanel, "card8");

        jSplitPane1.setRightComponent(outerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sidePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_sidePanelMouseDragged

    private void adminTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTabActionPerformed
        // TODO add your handling code here:
        adminPanel.setVisible(true);
        attendeePanel.setVisible(false);
        addPanel.setVisible(false);
        viewPanel.setVisible(false);
        updatePanel.setVisible(false);
        deletePanel.setVisible(false);
        statisticsPanel.setVisible(false);
    }//GEN-LAST:event_adminTabActionPerformed

    private void attendeeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeeTabActionPerformed
        // TODO add your handling code here:
        adminPanel.setVisible(false);
        attendeePanel.setVisible(true);
        addPanel.setVisible(false);
        viewPanel.setVisible(false);
        updatePanel.setVisible(false);
        deletePanel.setVisible(false);
        statisticsPanel.setVisible(false);

    }//GEN-LAST:event_attendeeTabActionPerformed

    private void outerStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerStatisticsActionPerformed
        try {
            // TODO add your handling code here:
            adminPanel.setVisible(false);
            attendeePanel.setVisible(false);
            addPanel.setVisible(false);
            viewPanel.setVisible(false);
            updatePanel.setVisible(false);
            deletePanel.setVisible(false);
            statisticsPanel.setVisible(true);
            
            pst = con.prepareCall("SELECT COUNT(Id), Country FROM attendee_info GROUP BY Country;");
            FetchStats(pst, statsTable);
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outerStatisticsActionPerformed

    private void outerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerSearchActionPerformed
        try {
            // TODO add your handling code here:
            adminPanel.setVisible(false);
            attendeePanel.setVisible(false);
            addPanel.setVisible(false);
            viewPanel.setVisible(true);
            updatePanel.setVisible(false);
            deletePanel.setVisible(false);
            statisticsPanel.setVisible(false);
            pst = con.prepareStatement("SELECT * FROM attendee_info");
            Fetch(pst, searchTable);
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outerSearchActionPerformed

    private void outerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerAddActionPerformed
        // TODO add your handling code here:
        adminPanel.setVisible(false);
        attendeePanel.setVisible(false);
        addPanel.setVisible(true);
        viewPanel.setVisible(false);
        updatePanel.setVisible(false);
        deletePanel.setVisible(false);
        statisticsPanel.setVisible(false);
    }//GEN-LAST:event_outerAddActionPerformed

    private void outerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerUpdateActionPerformed
        // TODO add your handling code here:
        adminPanel.setVisible(false);
        attendeePanel.setVisible(false);
        addPanel.setVisible(false);
        viewPanel.setVisible(false);
        updatePanel.setVisible(true);
        deletePanel.setVisible(false);
        statisticsPanel.setVisible(false);
    }//GEN-LAST:event_outerUpdateActionPerformed

    //adding an element
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            String name = txtName.getText();
            String mail = txtEmail.getText();
            String number = txtNumber.getText();
            String country = (String) txtCountry.getSelectedItem();
            
            pst = con.prepareStatement("INSERT INTO attendee_info (Name, Country, Contact_Number, Email) VALUES (?,?,?,?)");
            pst.setString(1, name);
            pst.setString(2, country);
            pst.setString(3, number);
            pst.setString(4, mail);
            
            int k = pst.executeUpdate();
            if (k==1){
                JOptionPane.showMessageDialog(this, "Record Added Successfully!");
                txtName.setText("");
                txtEmail.setText("");
                txtNumber.setText("");
                txtCountry.setSelectedIndex(-1);
            }
            else{
                JOptionPane.showMessageDialog(this, "Operation Failed! Please try again");
            }
                    
                    } catch(SQLIntegrityConstraintViolationException ex){
            JOptionPane.showMessageDialog(this, "Duplicate Entry for Email detected\nPlease enter a different Email address.");
        }
        catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            // TODO add your handling code here:
            String search = txtSearch.getText();
            pst = con.prepareStatement("SELECT * FROM attendee_info WHERE Email=?");
            pst.setString(1, search);
            Fetch(pst, searchTable);
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        try{
            String name = updateName.getText();
            String mail = updateEmail.getText();
            String number = updateNumber.getText();
            String country = (String) updateCountry.getSelectedItem();

            pst = con.prepareStatement("UPDATE attendee_info SET Name=?, Country=?, Contact_Number=? WHERE Email=?");
            pst.setString(1, name);
            pst.setString(2, country);
            pst.setString(3, number);
            pst.setString(4, mail);

            int k = pst.executeUpdate();
            if (k==1){
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                txtName.setText("");
                txtEmail.setText("");
                txtNumber.setText("");
                txtCountry.setSelectedIndex(-1);
            }
            else{
                JOptionPane.showMessageDialog(this, "Operation Failed! Please try again\nMake sure the email address you have entered is correct");
            }

            }
        catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            // TODO add your handling code here:
            String delId = deleteId.getText();
            pst = con.prepareStatement("DELETE FROM attendee_info WHERE Id=?");
            pst.setString(1, delId);
            int k = pst.executeUpdate();
            if (k==1){
                JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                deleteId.setText("");
                
                //updating the table view
                pst = con.prepareStatement("SELECT * FROM attendee_info");
                Fetch(pst, deleteTable);
            }
            else{
                JOptionPane.showMessageDialog(this, "Operation Failed! Please try again\nMake sure the email address you have entered is correct");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void outerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerDeleteActionPerformed
        try {
            // TODO add your handling code here:
            adminPanel.setVisible(false);
            attendeePanel.setVisible(false);
            addPanel.setVisible(false);
            viewPanel.setVisible(false);
            updatePanel.setVisible(false);
            deletePanel.setVisible(true);
            statisticsPanel.setVisible(false);
            
            pst = con.prepareStatement("SELECT * FROM attendee_info");
            Fetch(pst, deleteTable);
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outerDeleteActionPerformed

    private void countrySearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrySearchBtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String search = countrySearch.getText();
            pst = con.prepareStatement("SELECT * FROM attendee_info WHERE Country LIKE ?");
            pst.setString(1, '%'+search+'%');
            Fetch(pst, searchTable);
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_countrySearchBtnActionPerformed

    
    //displaying the values in a table
    public void FetchStats(PreparedStatement pst, JTable table){
        try {
            int columnCount;
            rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            columnCount = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel) table.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector<String> temp = new Vector<>();
                for(int c=1;c<=columnCount; c++){
                    temp.add(rs.getString("Country"));
                    temp.add(rs.getString("COUNT(Id)"));
                }
                df.addRow(temp);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //displaying the values in the table
    public void Fetch(PreparedStatement pst, JTable table){
        try {
            int columnCount;
            rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            columnCount = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel) table.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector<String> temp = new Vector<>();
                for(int c=1;c<=columnCount; c++){
                    temp.add(rs.getString("Id"));
                    temp.add(rs.getString("Name"));
                    temp.add(rs.getString("Country"));
                    temp.add(rs.getString("Contact_Number"));
                    temp.add(rs.getString("Email"));
                }
                df.addRow(temp);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(lab8_question1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton adminTab;
    private javax.swing.JPanel attendeePanel;
    private javax.swing.JButton attendeeTab;
    private javax.swing.JTextField countrySearch;
    private javax.swing.JButton countrySearchBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deleteId;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JTable deleteTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton outerAdd;
    private javax.swing.JButton outerDelete;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JButton outerSearch;
    private javax.swing.JButton outerStatistics;
    private javax.swing.JButton outerUpdate;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable searchTable;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JTable statsTable;
    private javax.swing.JComboBox<String> txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton updateBtn;
    private javax.swing.JComboBox<String> updateCountry;
    private javax.swing.JTextField updateEmail;
    private javax.swing.JTextField updateName;
    private javax.swing.JTextField updateNumber;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
